# Generated by Django 5.2.6 on 2025-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
